//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> idUser { get; set; }
        public string UserName { get; set; }
        public string PhoneUser { get; set; }
        public string EmailUser { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public Nullable<System.Guid> idShopingCart { get; set; }
        public Nullable<int> StatusDel { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.Guid> idShop { get; set; }
        public string ShopName { get; set; }
        public string PhoneShop { get; set; }
        public string AddressShop { get; set; }
        public Nullable<long> TotalQantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
