//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageProduct
    {
        public int ID { get; set; }
        public System.Guid idProduct { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
