//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public System.Guid ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> GiaNiemYet { get; set; }
        public Nullable<decimal> GiaSale { get; set; }
        public bool ConHang { get; set; }
        public Nullable<System.DateTime> GioBatDau { get; set; }
        public Nullable<System.DateTime> GioKetThuc { get; set; }
        public System.Guid idShop { get; set; }
        public Nullable<int> idLoaiSanPham { get; set; }
        public Nullable<int> StatusDel { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<int> idNhomSanPham { get; set; }
        public Nullable<int> LuotHienThi { get; set; }
        public Nullable<int> LuotXem { get; set; }
    }
}
