//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartDetail
    {
        public int ID { get; set; }
        public Nullable<System.Guid> idShoppingCart { get; set; }
        public Nullable<System.Guid> idProudct { get; set; }
        public string Image { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> StatusDel { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
